"""init

Revision ID: 01f6ea90dc29
Revises: 
Create Date: 2025-10-22 17:29:56.525974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f6ea90dc29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuesta')
    op.drop_table('partida')
    with op.batch_alter_table('partida_pregunta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_pp_orden'))

    op.drop_table('partida_pregunta')
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_jugador_alias'))

    op.drop_table('jugador')
    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_imagen_proveedor'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'proveedor_api', ['proveedor_id'], ['proveedor_id'])

    with op.batch_alter_table('opcion_respuesta', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_opcion_texto', ['pregunta_id', 'texto'])
        batch_op.drop_constraint(batch_op.f('fk_opcion_pregunta'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pregunta', ['pregunta_id'], ['pregunta_id'])

    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.alter_column('enunciado_hash_en',
               existing_type=mysql.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_pregunta_imagen'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pregunta_categoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pregunta_dificultad'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'imagen', ['imagen_id'], ['imagen_id'])
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['categoria_id'])
        batch_op.create_foreign_key(None, 'dificultad', ['dificultad_id'], ['dificultad_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregunta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pregunta_dificultad'), 'dificultad', ['dificultad_id'], ['dificultad_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_pregunta_categoria'), 'categoria', ['categoria_id'], ['categoria_id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_pregunta_imagen'), 'imagen', ['imagen_id'], ['imagen_id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('enunciado_hash_en',
               existing_type=sa.String(length=64),
               type_=mysql.CHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('opcion_respuesta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_opcion_pregunta'), 'pregunta', ['pregunta_id'], ['pregunta_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_constraint('uq_opcion_texto', type_='unique')

    with op.batch_alter_table('imagen', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_imagen_proveedor'), 'proveedor_api', ['proveedor_id'], ['proveedor_id'], onupdate='CASCADE', ondelete='RESTRICT')

    op.create_table('jugador',
    sa.Column('jugador_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('alias', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha_alta', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('jugador_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_jugador_alias'), ['alias'], unique=True)

    op.create_table('partida_pregunta',
    sa.Column('partida_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pregunta_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('nro_orden', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.partida_id'], name=op.f('fk_pp_partida'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.pregunta_id'], name=op.f('fk_pp_pregunta'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('partida_id', 'pregunta_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('partida_pregunta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_pp_orden'), ['partida_id', 'nro_orden'], unique=True)

    op.create_table('partida',
    sa.Column('partida_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('jugador_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_fin', mysql.TIMESTAMP(), nullable=True),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dificultad_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('num_preguntas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('puntaje_total', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.categoria_id'], name='fk_partida_categoria', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dificultad_id'], ['dificultad.dificultad_id'], name='fk_partida_dificultad', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugador.jugador_id'], name='fk_partida_jugador', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partida_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('respuesta',
    sa.Column('respuesta_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('partida_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pregunta_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('opcion_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('es_correcta', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('puntos_otorgados', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('respondida_en', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['opcion_id'], ['opcion_respuesta.opcion_id'], name=op.f('fk_resp_opcion'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partida_id'], ['partida.partida_id'], name=op.f('fk_resp_partida'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['pregunta.pregunta_id'], name=op.f('fk_resp_pregunta'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('respuesta_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
